# docs/conf.py

# -- Path setup --------------------------------------------------------------

import os
import sys
import sphinx_rtd_theme

# Add the project's root directory to sys.path to allow Sphinx to find the modules
# Assuming conf.py is inside the 'docs/' directory
sys.path.insert(0, os.path.abspath('..'))

# -- Project information -----------------------------------------------------

project = 'SectorAlarm'
author = 'Jonathan Petersson'  # Replace with your name
release = '1.2.0'     # Replace with your package's version

# Optionally, you can dynamically fetch the version from your package
# Uncomment the following lines if you prefer this approach

# import sectoralarm
# release = sectoralarm.__version__

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be extensions
# coming with Sphinx (named 'sphinx.ext.*') or your custom ones.

extensions = [
    'sphinx.ext.autodoc',             # Automatically document modules
    'sphinx.ext.napoleon',            # Support for NumPy and Google style docstrings
    'sphinx.ext.viewcode',            # Add links to highlighted source code
    'sphinx.ext.githubpages',         # Create .nojekyll file for GitHub Pages
    'sphinx_rtd_theme',               # Read the Docs theme
    # Add other extensions if needed
]

# Specify the suffix(es) of source filenames.
# You can specify multiple suffixes as a list of string values:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'  # Change to ['.rst', '.md'] if using Markdown

# The master toctree document.
master_doc = 'index'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.

exclude_patterns = [
    '_build',
    'Thumbs.db',
    '.DS_Store',
    'README.md',  # Exclude README if you have a separate index.rst
    # Add other patterns to exclude as needed
]

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.

# Use the Read the Docs theme
html_theme = 'sphinx_rtd_theme'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".

html_static_path = ['_static']

# -- Options for Autodoc -----------------------------------------------------

# Automatically generate documentation from docstrings
autodoc_member_order = 'bysource'  # Order members by their order in the source code
autodoc_default_options = {
    'members': True,
    'undoc-members': False,
    'private-members': False,
    'show-inheritance': True,
    'imported-members': False,
}

# -- Options for Napoleon ----------------------------------------------------

# Napoleon settings to parse Google/NumPy style docstrings
napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = False
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = False
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = False
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True

# -- Extension configuration -------------------------------------------------

# If you have any specific configurations for extensions, add them here.
# For example, configuring 'sphinx.ext.viewcode':

viewcode_follow_imported_members = True

# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.

htmlhelp_basename = 'SectorAlarmDoc'

# -- Options for LaTeX output ------------------------------------------------

# Grouping the document tree into LaTeX files. List of tuples
# where the first element is the source start file and the second
# is the target name.

latex_documents = [
    (master_doc, 'SectorAlarm.tex', 'SectorAlarm Documentation',
     'Jonathan Petersson', 'manual'),
]

# -- Options for manual page output ------------------------------------------

man_pages = [
    (master_doc, 'sectoralarm', 'SectorAlarm Documentation',
     [author], 1)
]

# -- Options for Texinfo output ----------------------------------------------

texinfo_documents = [
    (master_doc, 'SectorAlarm', 'SectorAlarm Documentation',
     author, 'SectorAlarm', 'One line description of project.',
     'Miscellaneous'),
]

# -- Miscellaneous ------------------------------------------------------------

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = 'en'

# List of patterns to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path.
exclude_patterns = []

# -- HTML Theme Options ------------------------------------------------------

# Customize the appearance of the Read the Docs theme
html_theme_options = {
    'navigation_depth': 4,
    'collapse_navigation': False,
    'display_version': True,
    'logo_only': False,
    'prev_next_buttons_location': 'bottom',
    'style_external_links': False,
    'vcs_pageview_mode': '',
    # 'canonical_url': '',
    # 'analytics_id': '',  # Provided by Google in your tracking code
    # 'logo': 'path/to/logo.png',
}

# -- Logo and favicon ---------------------------------------------------------

# If you have a logo, set the path here. The path is relative to the static directory.
# html_logo = 'images/logo.png'

# If you have a favicon, set the path here. The path is relative to the static directory.
# html_favicon = 'images/favicon.ico'

# -- Pygments Style -----------------------------------------------------------

# Choose a Pygments (syntax highlighting) style.
pygments_style = 'sphinx'

# -- Additional Files ---------------------------------------------------------

# If you have additional CSS or JavaScript files, specify them here.
# For example, to add a custom CSS file:
#
# html_css_files = [
#     'css/custom.css',
# ]
#
# And place 'custom.css' in the 'docs/_static/css/' directory.
